github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local execution

title: [Jakarta SOAP]
description: [Eclipse Implementation of Jakarta SOAP with Attachments]

links:
  source: https://github.com/eclipse-ee4j/metro-saaj/
  javadocs: https://javadoc.io/doc/com.sun.xml.messaging.saaj/saaj-impl/1.5.2
  download: https://search.maven.org/artifact/com.sun.xml.messaging.saaj/saaj-impl/1.5.2/jar
  mailinglist: https://accounts.eclipse.org/mailing-list/metro-dev
  
include:
  - LICENSE.md
  - CONTRIBUTING.md
